### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by DigiGoon** [halcyonproject/.github#4]
### Device To maintain

Mi 11X Pro (haydn)

### Device Tree Sources

Device Tree: https://github.com/DigiGoon/android_device_xiaomi_haydn
Common Device Tree: https://github.com/DigiGoon/android_device_xiaomi_sm8350-common
Kernel Source: https://github.com/DigiGoon/android_kernel_xiaomi_sm8350
Device Vendor Tree: https://gitlab.com/DigiGoon/proprietary_vendor_xiaomi_haydn
Common Vendor Tree: https://gitlab.com/DigiGoon/proprietary_vendor_xiaomi_sm8350-common

### Number of ROM's you maintain officially

0

### Any Exceptions/special concern?

No

### Telegram username

DigiGoon

### GitHub username

DigiGoon

### Logcat

[haydn_halcyon.log](https://github.com/halcyonproject/.github/files/12598015/haydn_halcyon.log)

**Comment by slcee** [comment]
Thank you for applying, welcome to the team.
