### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by ramsprojects** [halcyonproject/.github#5]
### Device To maintain

Poco M3 Pro / Redmi Note 10T / 10 5G / 11 SE (camellia)

### Device Tree Sources

Device tree: [ramsprojects/android_device_xiaomi_camellia](https://github.com/ramsprojects/android_device_xiaomi_camellia)
Vendor tree: [ramsprojects/android_vendor_xiaomi_camellia](https://github.com/ramsprojects/android_device_xiaomi_camellia)
Kernel tree: [ramsprojects/android_device_xiaomi_camellia-kernel](https://github.com/ramsprojects/android_device_xiaomi_camellia-kernel)

### Number of ROM's you maintain officially

2

### Any Exceptions/special concern?

Nothing

### Telegram username

@ramshell688

### GitHub username

@ramshell688

### Logcat

[logcat.log](https://github.com/halcyonproject/.github/files/12697646/logcat.log)

**Comment by herobuxx** [comment]
@ramshell688  is also you?

**Comment by ramsprojects** [comment]
> @ramshell688 is also you?

Yeah it's me, my group name [@ramsprojects](https://t.me/ramsprojects)

**Comment by ramshell688** [comment]
Sorry, I should have apply with this account

**Comment by herobuxx** [comment]
Tree looks good to me

Welcome to the team!

**Comment by herobuxx** [comment]
Go ahead PM me on t.me/herobuxx

**Comment by herobuxx** [comment]
You may now do a PR on our wiki to add your device in
