### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by User132New** [halcyonproject/.github#6]
### Device To maintain

Redmi Note 10S/ 11 SE India(rosemary/secret)

### Device Tree Sources

Device Tree : https://github.com/User132New/android_device_redmi_rosemary
Device Kernel : https://github.com/User132New/android_kernel_redmi_rosemary
Device Vendor : https://github.com/User132New/android_vendor_redmi_rosemary
Device Vendor Firmware : https://github.com/User132New/android_vendor_redmi_rosemary-firmware

### Number of ROM's you maintain officially

0

### Any Exceptions/special concern?

No.

### Telegram username

@bera_nhi  & @KrugerBeru

### GitHub username

User132New & windowz414

### Logcat

Logcat : https://drive.google.com/file/d/1cntt2aPyAa2rZQmajhOAztQ1mwkJeB1K/view?usp=drive_link
[rosemarylog.txt](https://github.com/halcyonproject/.github/files/12708648/rosemarylog.txt)

**Comment by slcee** [comment]
Are the two usernames referring to the same person?

**Comment by User132New** [comment]
> Are the two usernames referring to the same person?

No, they are different..
@KrugerBeru is co-maintainer with me @bera_nhi

**Comment by windowz414** [comment]
> Are the two usernames referring to the same person?

KrugerBeru Telegram account belongs to me, and I wanted to opt in as a co-maintainer.
